name: OpenRV

on:
  push:
    # Skip jobs when only those files are changed.
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'Notice.txt'
      - 'rvcmds.sh'

  pull_request:
    # Skip jobs when only those files are changed.
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'Notice.txt'
      - 'rvcmds.sh'

  schedule:
    # Midnight build every day
    - cron: "0 0 * * *"

  # This allows manual triggering of the workflow from the web
  workflow_dispatch:
    inputs:
      SKIP_DEPS_CACHE:
        description: 'Skip dependencies caching'
        required: true
        default: 'false'

env:
  SKIP_DEPS_CACHE: 'false'

jobs:
  macos:
    name: '${{ matrix.os }} ${{ matrix.arch-type }} ${{ matrix.vfx-platform }}
      <qt=${{ matrix.qt-version }},
       python=${{ matrix.python-version }},
       arch=${{ matrix.arch-type }},
       config=${{ matrix.build-type }}>'

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "macos-14"
            arch-type: "arm64"
            build-type: "Release"
            qt-version: "5.15.15"
            python-version: "3.11"
            vfx-platform: "CY2023"
    steps:
      - name: Display disk space
        run: |
          df -h /
          
      - name: Clear up some spaces on disk
        run: |
          # Remove some unused XCode (Default is XCode 15.4).
          sudo rm -rf /Applications/Xcode_15.3.app
          sudo rm -rf /Applications/Xcode_15.2.app
          sudo rm -rf /Applications/Xcode_15.1.app
          sudo rm -rf /Applications/Xcode_15.0.1.app
          sudo rm -rf /Users/runner/Library/Android

      - name: Display disk space
        run: |
          df -h /

      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
        with:
          submodules: recursive

      - name: Add repository as safe directory
        run: |
          git config --global --add safe.directory /__w/OpenRV/OpenRV
          
      - name: Prepare Qt folder
        run: |
          mkdir -p "${{ github.workspace }}/deps"

      - name: Build Qt
        if: matrix.arch-type == 'arm64'
        id: build-qt5-for-arm64
        uses: ./.github/actions/build-qt5-for-arm64
        with:
          qt-version: "5.15.15"
          python3-version: "3.11.9"
          python2-version: "2.7.18"
          xcode-version: "14.3.1"
          qt-output: "deps"

      - name: Activate Python ${{ matrix.python-version }} if Qt was taken from cache
        if: steps.build-qt5-for-arm64.outputs.qt-cache-hit == 'true'
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # 5.2.0
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --user --upgrade -r requirements.txt
  
      - name: Install Homebrew dependencies
        run: |
          brew install --quiet --formula cmake ninja readline sqlite3 xz zlib tcl-tk autoconf automake libtool python yasm clang-format black meson nasm pkg-config glew

      - name: Set QT_HOME
        if: matrix.arch-type == 'arm64'
        run: |
          echo "QT_HOME=${{ github.workspace }}/deps" >> $GITHUB_ENV

      - name: Check if the dependencies changed
        if: matrix.build-type == 'Release'
        uses: dorny/paths-filter@v3
        id: changes-in-deps
        with:
          filters: |
            dependencies:
              - 'cmake/**'
  
      - name: Restore some dependencies
        # Restore only if there are no changes under cmake folder and Release build.
        if: env.SKIP_DEPS_CACHE == 'false' && steps.changes-in-deps.outputs.dependencies == 'false' && matrix.build-type == 'Release'
        id: cmake-dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./_build/RV_DEPS_*
            ./_build/cmake/dependencies
            ./_build/_deps
          key: macos-${{ matrix.arch-type }}-dependencies

      - name: Configure OpenRV
        run: |
          cmake -B _build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DRV_DEPS_QT5_LOCATION=$QT_HOME -DRV_VFX_PLATFORM=${{ matrix.vfx-platform }}
   
      - name: Build OpenRV dependencies
        if: steps.cmake-dependencies.outputs.cache-hit != 'true'
        run: |
          cmake --build _build --config ${{ matrix.build-type }} --target dependencies --parallel=$(python -c 'import os; print(os.cpu_count())') -v
          ls -al _build
          
      - name: Build OpenRV main executable
        run: |
          cmake --build _build --config ${{ matrix.build-type }} --target main_executable --parallel=$(python -c 'import os; print(os.cpu_count())') -v

      - name: Tests
        run: |
          ctest --test-dir _build -C ${{ matrix.build-type }} --extra-verbose

      - name: Install OpenRV
        run: |
          cmake --install _build --prefix $(pwd)/_install --config ${{ matrix.build-type }}
